### ISSUE TITLE
Feature Suggestion: Use Poetry for Dependency Management

### ISSUE THREAD

**Issue by biodrone** [2t6h/puregym-attendance#3]
Hi! Pumped to see that this exists and works, planning on eventually folding it into a HomeAssistant widget with regular updates.

I usually manage dependencies with Poetry just because it's pretty easy to maintain and cleans up the readme so you're not having to mention individual packages (you just have to get people to do `pip install poetry && poetry install` every time). 

I've added that detail to my branch `feat/use-poetry` and would be happy to PR that if you think it'd be useful?

Thanks!

**Comment by 2t6h** [comment]
That would be a great addition. Thanks.
