### ISSUE TITLE
How did you find the endpoints?

### ISSUE THREAD

**Issue by Smaug123** [2t6h/puregym-attendance#4]
Many thanks for this - you've done the Lord's work.

Did you have a systematic way to obtain these endpoints? Emulating Android to intercept its network calls seems like more work than I want to do, and I don't know an easy way to set up a proxy on my Android phone. The Swagger endpoint at capi.puregym.com/swagger requires OAuth and does not answer to my bearer token. Is there an easier way than any of the above?

**Comment by fk128** [comment]
If you're looking for the session visit history, it's at this endpoint: /api/v2/gymSessions/member?fromDate=2020-01-01T00:00:00&toDate=2023-10-01T00:00:00 . Found by emulating Android.

**Comment by 2t6h** [comment]
Hi, great to see open sourcing this has helped a few people. I sniffed the packets from the puregym ios app using the Charles Proxy app. Hope this helps.
